### ISSUE TITLE
issue in feature extraction system

### ISSUE THREAD

**Issue by Arsalan66** [Vision4UAV/Aerostack#54]
I have written python a program for feature extraction system to find contours on image :
#!/usr/bin/env python

import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
import sys

bridge = CvBridge()

def image_callback(ros_image):
  print 'got an image'
  global bridge
  #convert ros_image into an opencv-compatible image
  try:
    cv_image = bridge.imgmsg_to_cv2(ros_image, "bgr8")
  except CvBridgeError as e:
      print(e)
  #from now on, you can work exactly like with opencv
def read_rgb_image(image_name, show):
    rgb_image = cv2.imread(image_name)
    if show: 
        cv2.imshow("RGB Image",rgb_image)
    return rgb_image

def convert_rgb_to_gray(rgb_image,show):
    gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)
    if show: 
        cv2.imshow("Gray Image",gray_image)
    return gray_image

def convert_gray_to_binary(gray_image, adaptive, show):
    if adaptive: 
        binary_image = cv2.adaptiveThreshold(gray_image, 
                            255, 
                            cv2.ADAPTIVE_THRESH_GAUSSIAN_C, 
                            cv2.THRESH_BINARY_INV, 115, 2)
    else:
        _,binary_image = cv2.threshold(gray_image,127,255,cv2.THRESH_BINARY_INV)
    if show:
        cv2.imshow("Binary Image", binary_image)
    return binary_image    

def getContours(binary_image):      
    contours, hierarchy = cv2.findContours(binary_image, 
                                              cv2.RETR_TREE, 
                                               cv2.CHAIN_APPROX_SIMPLE)
    return contours

def draw_contours(image, contours, image_name):
    index = -1 #means all contours
    thickness = 2 #thinkess of the contour line
    color = (255, 0, 255) #color of the contour line
    cv2.drawContours(image, contours, index, color, thickness)
    cv2.imshow(image_name,image)

  
def main(args):
    rospy.init_node('image_converter', anonymous=True)
    image_name = rospy.Subscriber("/hummingbird_adr1/camera_front/image_raw",Image, image_callback)
    rgb_image = read_rgb_image(image_name, True)
    yellowLower =(30, 150, 100)
    yellowUpper = (50, 255, 255)
    
    binary_image_mask = filter_color(rgb_image, yellowLower, yellowUpper)
    contours = getContours(binary_image_mask)
    draw_ball_contour(binary_image_mask, rgb_image,contours)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main(sys.argv)

However it gives the following issue:
Traceback (most recent call last):
  File "./aero.py", line 76, in <module>
    main(sys.argv)
  File "./aero.py", line 62, in main
    rgb_image = read_rgb_image(image_name, True)
  File "./aero.py", line 22, in read_rgb_image
    rgb_image = cv2.imread(image_name)
TypeError: expected string or Unicode object, Subscriber found

can anyone kindly help me solve this problem?

**Comment by Arsalan66** [comment]
i want to manipulate drone's camera in bridge inspection project
